# Generated by Django 3.1.1 on 2020-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
