# Generated by Django 3.1.1 on 2020-10-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileHandler', '0002_profile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
