# Generated by Django 3.1.1 on 2020-10-24 12:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(max_length=200)),
                ('subject_color', colorfield.fields.ColorField(default='#184336', max_length=18)),
            ],
        ),
    ]
