# Generated by Django 3.1.1 on 2020-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsubject',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
    ]
