# Generated by Django 3.1.1 on 2020-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_subject',
            field=models.CharField(max_length=10),
        ),
    ]
