# Generated by Django 3.1.1 on 2020-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_auto_20201017_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_content',
            field=models.TextField(default=''),
        ),
    ]
