# Generated by Django 3.1.1 on 2020-10-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_blogpost_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='basic_avatar.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_author',
            field=models.IntegerField(default='basic_avatar.png'),
        ),
    ]
