# Generated by Django 3.1.1 on 2020-10-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_auto_20201023_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_author',
        ),
    ]
