# Generated by Django 3.1.1 on 2020-10-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_remove_blogpost_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
