# Generated by Django 3.1.1 on 2020-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_remove_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_author',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
    ]
