# Generated by Django 3.1.1 on 2020-10-28 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogposts', '0008_blogpost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
