# Generated by Django 3.1.1 on 2020-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0010_auto_20201028_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='likers',
            field=models.TextField(default='{ "data":[] }'),
        ),
    ]
